[pytest]
addopts =
    --doctest-modules
    --doctest-glob=*.txt
    --ignore=kotti_image/templates/
    --tb=short
    kotti_image/tests
python_files = test*py
markers =
    user: mark test to be run as the given user
