[pytest]
# if you use PyCharm / IDEA and want to debug the tests,
# you have to remove ``--cov`` and ``--cov-report`` from ``addopts``,
# otherwise your breakpoints won't be hit.
# See: https://stackoverflow.com/questions/40718760/unable-to-debug-in-pycharm-with-pytest
addopts =
    --ignore=kotti/templates/
    --capture=no
    --strict
    --tb=short
    kotti/
python_files = test_*.py
markers =
    user: mark test to be run as the given user
    slow: mark test to be run only with --runslow option
