[pytest]
addopts =
    --doctest-modules
    --doctest-glob=*.txt
    --ignore=kotti_tinymce/templates/
    --tb=short
    kotti_tinymce/
python_files = test_*.py
markers =
    user: mark test to be run as the given user
